version: '3'
services:
  api:
    image: jusan-fastapi-final:dockerized
    container_name: jusan-compose-final
    restart: always
  nginx:
    image: nginx:mainline
    container_name: jusan-nginx-final
    depends_on:
      - api
    restart: always
    ports:
      - "8787:80"
    volumes:
      - ./jusan-docker-mount.conf:/etc/nginx/nginx.conf:ro
      - ./jusan-fastapi-final.conf:/etc/nginx/conf.d/jusan-fastapi-final.conf:ro
      - ./jusan-docker-mount:/mnt/jusan-docker-mount:ro